### ISSUE TITLE
Normalize CAS Attributes

### ISSUE THREAD

**Issue by Punt13140** [ecphp/cas-bundle#93]
Hello @drupol ,

I noticed that you have released a new major version of the bundle, so I wanted to see if the modifications could be easily integrated into our applications.

After a few tweaks (because we're overriding some of your bundle's functionalities), it seems to work.

I have a small question regarding the attributes returned by CAS.

The table returned doesn't seem "normalized".

Example of attributes with version ^2.5: 
```php
[
  "mail" => "toto.toto@toto.fr",
  "displayName" => "Toto TOTO",
  // ...
]
```

Attributes with version ^3.0 : 
```php
[
  "mail" => [
     0 => "toto.toto@toto.fr"
  ],
  "displayName" => [
     0 => "Toto TOTO"
  ],
  // ...
]
```

Is there a method, such as passing a parameter to the login function, to normalize attributes? I could certainly extend my User class or modify the constructor, but I wonder if the CAS library could handle this normalization internally?

Thanks

**Comment by drupol** [comment]
Hello!

Thanks for opening the issue.

I guess you're talking about the new version ^3?
Are you using CAS with XML or JSON ?
I guess you're using XML but I may be wrong.

If you're using XML, this is indeed the default behaviour now since we've updated the library that parses it (https://github.com/ecphp/cas-lib/blob/master/src/Utils/Response.php).

I don't like saying that but if you want to use this version, I guess you'll have to follow the upgrade path and update your own code.

**Comment by Punt13140** [comment]
Yes, I am referring to version ^3.

I've identified the problem. Upon using version ^3, I encountered an error with xml_decode. I switched to JSON, which worked well, aside from the issue with attribute normalization.

After reverting to XML, I found I needed to explicitly require veewee/xml in my Symfony application, which resulted in the attributes being formatted as they were in version ^2.5/XML. However, I am puzzled as to why veewee/xml was not automatically installed, given that it is listed as a dependency.

**Comment by drupol** [comment]
So, your problem is solved? Glad to hear it :)

> After reverting to XML, I found I needed to explicitly require veewee/xml in my Symfony application, which resulted in the attributes being formatted as they were in version ^2.5/XML. However, I am puzzled as to why veewee/xml was not automatically installed, given that it is listed as a dependency.

There are at least 3 reasons why I don't install by default:

1. It requires the PHP extension `xsl` which might not be available by default
2. The `xsl` extension doesn't work on Windows machine (_CI is currently broken because of that_)
3. If you don't use XML in CAS, there's no need to have that dependency 

Let me know if I can be more helpful, if not, feel free to close the issue.

Thanks!

**Comment by Punt13140** [comment]
Ok, thanks for clarifying everything.

And thank you for the quick feedback, as always.
